etailor/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

etailor/etailor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from tailor.views import router
#from .views import router





urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('tailor.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

etailor/tailor/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
	path('', views.product_list, name='product_list'),
	url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    #path('<int:category_slug>)/', views.product_list, name='product_list_by_category'),
    #path('<int:id><int:slug>)/', views.product_detail, name='product_detail'),
]

etailor/tailor/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.id, self.slug])

etailor/tailor/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

from rest_framework import generics
from rest_framework.viewsets import ModelViewSet
from .serializers import CategorySerializer, ProductSerializer
from rest_framework.routers import DefaultRouter



def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'detail.html', context)


class CategoryViewSet(ModelViewSet):
	queryset = Category.objects.all()
	serializer_class = CategorySerializer

class CategoryDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

class ProductViewSet(ModelViewSet):
	queryset = Product.objects.all()
	serializer_class = ProductSerializer

class ProductDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer    


router = DefaultRouter()
router.register('category', CategoryViewSet)
router.register('product', ProductViewSet)

etailor/tailor/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} E-Tailor: Welcome{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% include 'navbar.html' %}

<div class="container">
    <div class="row" style="margin-top: 6%">
         <button class="btn btn-info pull-right">
            {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                    My Sewing Order:
                    <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                        {{ totail_items }} item{{ totail_items|pluralize }}, Tk. {{ cart.get_total_price }}
                    </a>
                    {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
         </button>
    </div>
</div>
{% block content %}


{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

etailor/tailor/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Services {% endif %}
{% endblock %}

{% block content %}
   <div class="container">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                <div class="card">
                    <div class="card-body">
                        <div class="col-md-6 text-right">
                            <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 170px; width: auto">
                        </div>
                        <div class="col-md-6" style="padding-left: 20px">
                            <h3>{{ product.name }}</h3>
                            <h6><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>

                            <p class="text-muted">Tk. {{ product.price }}</p>
                            <p>{{ product.description|safe|linebreaksbr }}</p>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {% csrf_token %}
                                {{ cart_product_form }}
                               <div>Color</div>
                                <select name="attr" id="" class="form-control" placeholder="Select Color">
                                  <option value="">Red</option>
                                  <option value="">Black</option>
                                  <option value="">White</option>
                                  <option value="">Green</option>
                                </select>
                                <div>Size :</div>
                                <select name="attr" id="" class="form-control" placeholder="Select Size">
                                  <option value="">S</option>
                                  <option value="">M</option>
                                  <option value="">L</option>
                                  <option value="">XL</option>
                                  <option value="">XXL</option>
                                </select>

                                <input type="submit" value="add to cart" class="btn btn-primary">
                            </form>
                            
                        </div>
                    </div>
                </div>
              </div>


          </div>

        </div>
      </div>

    </div>
{% endblock %}

etailor/tailor/templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Services {% endif %}
{% endblock %}

{% block content %}
   <div class="container-fluid">
      <div class="row" style="margin-top: 6%">


        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="">
            <h4>Sewing Category</h4>
            <ol class="list-unstyled">
              <li {% if not category %} class="active"{% endif %}><a href="{% url 'product_list' %}">All</a></li>
            {% for c in categories %}

              <li {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}
            </ol>
          </div>
        </div>



        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                  {% for product in products %}
                      <div class="col-md-4">
                        <div class="thumbnail">
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                            </a>
                            <div class="caption">
                                <h3 class="text-center">
                                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                </h3>
                                <p class="text-center">Tk. {{ product.price }}</p>
                            </div>
                        </div>
                      </div>
                  {% endfor %}
              </div>


          </div>

        </div>



      </div>

    </div>
{% endblock %}

etailor/tailor/templates/navbar.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0px; background-color: #5AC8FA;">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container-fluid">
      <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'product_list' %}" style="color: #ffffff">E- Tailor</a>
    </div>

    <div class="navbar-header navbar-center">
    <a class="navbar-brand" href="{% url 'product_list' %}" style="color: #ffffff">Home</a>
    <a class="navbar-brand" href="{% url 'product_list' %}" style="color: #ffffff">About </a>
    <a class="navbar-brand" href="{% url 'product_list' %}" style="color: #ffffff">How to Work</a>
    <a class="navbar-brand" href="{% url 'product_list' %}" style="color: #ffffff"> Contact Us</a>
     </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
          {% if request.user.is_authenticated %}
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">{{ request.user.username }}<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'logout' %}">logout</a></li>
            {% else %}
          <li class="divider"></li>
          <li><a href="{% url 'login' %}" style="color: #ffffff">Log in</a></li>
         <li><a href="{% url 'register' %}" style="color: #ffffff">Register</a></li>
        </ul>
         {% endif %}
      </li>
    </ul>
  </div>
  </div>
</nav>